### ISSUE TITLE
How can I scale the generated mesh?

### ISSUE THREAD

**Issue by DewaldBodenstein** [mattak/TopoMap#1]
Hay Mattak, I came accross this repo and am trying to make use of it in my Unity project. I am rendering Mapzen terrarium tiles as Terrain objects and want to get water generated from Mapzen's topojson tiles. Your TopoMap project is creating the polygons as expected but I want to rescale them to fit etc. Any chance you could point me to a resource that I can go through to understand your TopoMap renderer better?

**Comment by mattak** [comment]
Hi, @DewaldBodenstein !

Thanks for your interests.
TopoMap is my experimental project to generate unity mesh by using topojson.
So there are no docs for understanding how to it works.
[SampleTopoMapRenderer](https://github.com/mattak/TopoMap/blob/master/Assets/Plugins/TopoMap/Examples/Japan/SampleTopoMapRenderer.cs#L14) is the only sample code.


TopoMap performs two operations.

1. Convert topojson arcs to latitude and longitude points ([TopoPolygon.CreateVerts](https://github.com/mattak/TopoMap/blob/80060e2b7aa389e45529f30ade4cab16ab0ca003/Assets/Plugins/TopoMap/Examples/Japan/SampleTopoMapRenderer.cs#L57))
2. Create a polygon from points of latitude and longitude ([TopoPolygon.CreatePolygon](https://github.com/mattak/TopoMap/blob/80060e2b7aa389e45529f30ade4cab16ab0ca003/Assets/Plugins/TopoMap/Examples/Japan/SampleTopoMapRenderer.cs#L65))

Take the Tokyo Tower as example.

```tokyo_tower.topojson:json
{
  "type": "Topology",
  "objects": {
    "tokyo_tower": {
      "type": "GeometryCollection",
      "geometries": [
        {
          "type": "Polygon",
          "arcs": [
            [
              0
            ]
          ],
          "properties": {
            "name": "tokyo tower area"
          }
        }
      ]
    }
  },
  "arcs": [
    [
      [
        0,
        1
      ],
      [
        0,
        -1
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        -1,
        0
      ]
    ]
  ],
  "bbox": [
    139.74507099367815,
    35.658351698353314,
    139.7459185717281,
    35.658961904196815
  ],
  "transform": {
    "scale": [
      0.0008475780499566099,
      0.0006102058435004665
    ],
    "translate": [
      139.74507099367815,
      35.658351698353314
    ]
  }
}
```

Since topojson is mutually convertible with geojson, it can be represented by geojson as follows.


```tokyo_tower.geojson:json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "tokyo tower area"
      },
      "geometry": {
        "coordinates": [
          [
            [
              139.74507099367815,
              35.658961904196815
            ],
            [
              139.74507099367815,
              35.658351698353314
            ],
            [
              139.7459185717281,
              35.658351698353314
            ],
            [
              139.7459185717281,
              35.658961904196815
            ],
            [
              139.74507099367815,
              35.658961904196815
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}
```

[TopoPolygon.CreateVerts](https://github.com/mattak/TopoMap/blob/80060e2b7aa389e45529f30ade4cab16ab0ca003/Assets/Plugins/TopoMap/Scripts/Core/TopoPolygon.cs#L30) is the conversion of latitude and longitude to a point cloud transformation that corresponds to the above geometry.coordinates.
These verts are converted by using world position (0, 0).
After that, TopoPolygon.CreatePolygon makes Mesh using verts and creates GameObject with MeshRenderer, MeshFilter component.

I understand that you want to rescale the object,
The center of the generated polygon is at world position (0,0), so a simple scaling would produce unexpected results.

e.g. 2x scale (world origin rescale)
1. gameobject.transform.localScale = Vector3.one * 2;
- (139.74507099367815, 35.658961904196815) => (279.4901419873563, 71.31792380839363)
- (139.74507099367815, 35.658351698353314) => (279.4901419873563, 71.31670339670663)
- (139.7459185717281, 35.658961904196815) => (279.4918371434562, 71.31792380839363)
- (139.7459185717281, 35.658351698353314) => (279.4918371434562, 71.31670339670663)

I think what you probably want to do is rescale from the center position of the object, so you need to find the center position after TopoJson.CreateVerts, convert verts from that center position, and translate game object center before scaling.

e.g. 2x scale (object center rescale)
1. calculate center of object (139.74549478270313, 35.658656801275065)
2. remap verts from center
- (139.74507099367815, 35.658961904196815) => (0.0008475780499566099, 0.0006102058435004665)
- (139.74507099367815, 35.658351698353314) => (0.0008475780499566099, -0.0006102058435004665)
- (139.7459185717281, 35.658961904196815) => (-0.0008475780499566099, 0.0006102058435004665)
- (139.7459185717281, 35.658351698353314) => (-0.0008475780499566099, -0.0006102058435004665)
3. create gameobject and translate center to (139.74549478270313, 35.658656801275065)
4. rescale gameobject.

I hope this information would solve your problem!
